### ISSUE TITLE
Header guards?

### ISSUE THREAD

**Issue by gssgh** [malte-v/VulkanMemoryAllocator-Hpp#1]
Is there any reason why there is no header guards in vk_mem_alloc.hpp? If not, I think it'd be nice to have them. Since vk_mem_alloc.h uses AMD_VULKAN_MEMORY_ALLOCATOR_H I suggest using AMD_VULKAN_MEMORY_ALLOCATOR_HPP or something similar.

**Comment by malte-v** [comment]
My mistake, fixed it. Thanks for reporting!
