### ISSUE TITLE
Update to VMA 2.3.0

### ISSUE THREAD

**Issue by adam-sawicki-a** [malte-v/VulkanMemoryAllocator-Hpp#3]
Vulkan Memory Allocator is now at version 2.3.0-alpha.1. It's backward compatible, but there are many additions since 2.2.0. All new symbols are mentioned in CHANGELOG.md. You can update this project to use the new version.

**Comment by johannesugb** [comment]
Is this library still maintained? 

Another question: Is this library auto-generated (just like Vulkan-Hpp, as I suppose) or is it manual labour?

**Comment by malte-v** [comment]
1) Pretty much no. I can add you as a collaborator or transfer the repository to you if you are willing to maintain the project.
2) It *was* autogenerated by feeding the Vulkan-Hpp generator with a handwritten XML file. There was still a lot of manual work needed though, IIRC. I apparently don't have the XML anymore so the best way to update the library would probably be to just add the new features manually.

**Comment by johannesugb** [comment]
Thank you for the information. I am just starting to use VMA, so I can't tell yet if I can/want to maintain this project. But I might be willing to do so in a few months after I have made myself sufficiently familiar with VMA. I'll get back to you then.

**Comment by kidrigger** [comment]
The PR is supposed to update to 2.3 it would be nice for others to test it before merge.

@johannesugb if you still have a need.

**Comment by YaaZ** [comment]
@malte-v Hey! I'm now working on a script which generates these bindings from VMA code, can try maintaining this project if you don't mind

**Comment by malte-v** [comment]
Great, I'll happily accept a PR with a script that can generate the bindings in a manner that is compatible ti the current bindings (originally, I've used the Vulkan-Hpp generator as a starting point, IIRC). If that works out, I'll add you as a collaborator.

**Comment by YaaZ** [comment]
Sure, I'll create a PR when it's ready
